name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    steps:
      - name: Configure NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
          echo '@JackHowa:registry=https://npm.pkg.github.com' >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install
        run: npm ci
      
      - name: Publish
        run: npm run release:force
